-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."candidatesUsers"
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    birth_year character varying(4) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."employersUsers"
(
    user_id integer NOT NULL,
    company_name character varying(70) NOT NULL,
    web_site character varying(70) NOT NULL,
    phone_number character varying(20) NOT NULL,
    is_verified "char" NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL,
    title_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."staffUsers"
(
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    email character varying(70) NOT NULL,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."candidatesUsers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."employersUsers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public."staffUsers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;